/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;


public class userPrompt extends javax.swing.JFrame {
    private Journal pJournal;
    private MainMenu mainmenu;
    private Ledger ledger;
    /**
     * Creates new form userPrompt
     */
    public userPrompt(String en, Journal journal, MainMenu main, Ledger ldg) {
        initComponents();
        mainmenu = main;
        this.pJournal = journal;
        ledger = ldg;
        jLabel3.setText(en);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        cboxCredit = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        cboxDebit = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(244, 237, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(245, 238, 230));
        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User");
        jLabel3.setIconTextGap(18);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 570, 90));

        jPanel4.setBackground(new java.awt.Color(109, 148, 197));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(244, 237, 230));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRANSACTIONS");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 580, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setPreferredSize(new java.awt.Dimension(220, 220));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -30, 290, 180));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1340, 70));

        jPanel5.setBackground(new java.awt.Color(203, 220, 235));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Montserrat Black", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(75, 73, 67));
        jLabel5.setText("Enter Amount:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 400, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel7.setText("Particular:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 410, 30));

        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel2.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, 390, 60));

        jPanel6.setBackground(new java.awt.Color(203, 220, 235));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 30));

        cboxCredit.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        cboxCredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accumulated Depreciation", "Accounts Payable", "Accounts Receivable", "Advertisement Expense", "Bonds Payable", "Bonds Receivable", "Building", "Cash", "Capital/Equity", "Cost of Goods Sold (COGS)", "Depreciation Expense", "Equipment", "Furnitures & Fixtures", "Insurance Expense", "Interest Expense", "Inventories", "Land", "Liabilities", "Machineries", "Notes Payable", "Notes Receivable", "Prepaid Expenses", "Rent Expense", "Salaries Expense", "Sales", "Sales Discount", "Sales Returns and Allowances", "Service Revenue", "Supplies", "Supplies Expense", "Uncollectible Accounts Expense", "Unearned Revenues", "Utilities Expense", "Vehicles", "Withdrawals" }));
        cboxCredit.setSelectedIndex(-1);
        cboxCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCreditActionPerformed(evt);
            }
        });
        jPanel2.add(cboxCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 310, 60));

        jLabel9.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel9.setText("Particular:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 400, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(75, 73, 67));
        jLabel4.setText("CREDIT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 260, 70));

        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(75, 73, 67));
        jLabel6.setText("DEBIT");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 260, 70));

        jButton2.setBackground(new java.awt.Color(109, 148, 197));
        jButton2.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(244, 237, 240));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 740, 130, 40));

        cboxDebit.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        cboxDebit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accumulated Depreciation", "Accounts Payable", "Accounts Receivable", "Advertisement Expense", "Bonds Payable", "Bonds Receivable", "Building", "Cash", "Capital/Equity", "Cost of Goods Sold (COGS)", "Depreciation Expense", "Equipment", "Furnitures & Fixtures", "Insurance Expense", "Interest Expense", "Inventories", "Land", "Liabilities", "Machineries", "Notes Payable", "Notes Receivable", "Prepaid Expenses", "Rent Expense", "Salaries Expense", "Sales", "Sales Discount", "Sales Returns and Allowances", "Service Revenue", "Supplies", "Supplies Expense", "Uncollectible Accounts Expense", "Unearned Revenues", "Utilities Expense", "Vehicles", "Withdrawals" }));
        cboxDebit.setSelectedIndex(-1);
        cboxDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDebitActionPerformed(evt);
            }
        });
        jPanel2.add(cboxDebit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 310, 60));

        jButton1.setBackground(new java.awt.Color(109, 148, 197));
        jButton1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(245, 238, 230));
        jButton1.setText("Add Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 740, 190, 40));

        jButton3.setBackground(new java.awt.Color(109, 148, 197));
        jButton3.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(244, 237, 230));
        jButton3.setText("RETURN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 30));

        jPanel8.setBackground(new java.awt.Color(255, 232, 195));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 680, 160));

        jPanel9.setBackground(new java.awt.Color(255, 232, 195));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 680, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 1000));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 1340, 1010));

        jPanel7.setBackground(new java.awt.Color(203, 220, 235));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void cboxCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCreditActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        txtAmount.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboxDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDebitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxDebitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String amount = txtAmount.getText().trim();
        Object dob = cboxDebit.getSelectedItem();
        Object cob = cboxCredit.getSelectedItem();
        if(dob == null || cob == null){
            JOptionPane.showMessageDialog(this,"Please select both debit and credit accounts.");
            return;
        }
        String debits = dob.toString();
        String credits = cob.toString();
        
        if (amount.isEmpty()){
            JOptionPane.showMessageDialog(this, "No amount");
            return;
        }
        try {
            Double.parseDouble(amount);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid amount");
            return;
        }
        
        if (pJournal == null) {
            JOptionPane.showMessageDialog(this, "Cannot access the General Journal");
            return;
        }
        
        if (debits.equals(credits)){
            JOptionPane.showMessageDialog(this, "Debit and Credit connot have the same account ");
            return;
        }
        
        pJournal.recTransaction(debits, credits, amount);
        
        
        JOptionPane.showMessageDialog(this, "Transaction successfully added to Journal.");
        
        txtAmount.setText("");
        cboxCredit.setSelectedIndex(-1);
        cboxDebit.setSelectedIndex(-1);
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainmenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxCredit;
    private javax.swing.JComboBox<String> cboxDebit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
